---
title: "Module 2: Model Assessment and Diagnostics for SLR"
author: "tqin"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}
# Only need to run on first use and then can comment out

# install.packages('lmtest')
# install.packages('onewaytests')
```

```{r}
library(alr4)
library(ALSM)
library(car)
library(lmtest)
library(onewaytests)
library(lmtest)
library(MASS)
```

```{r}
toluca <- read.csv("C:/Users/arthur22/Downloads/toluca.csv")
colnames(toluca)<-c("size","hour")
summary(toluca)
length(toluca[,1])
toluca$size
```

```{r}
qf(0.95,1,23)
qf(0.95,1,14)
qt(1-0.1/10,23)
```

```{r LSM}
toluca.mod<-lm(hour~size, toluca)
summary(toluca.mod)
anova(toluca.mod)
cor.test(toluca$hour,toluca$size, conf.leve=0.95)

qf(0.95,1,23)
```

```{r The coefficient of determination, Rsquare, between X and Y}
cor(toluca)
r2<-cor(toluca)^2
r2
```

```{r HT on correlation r}

r=cor(toluca$hour,toluca$size);
cor.test(toluca$hour,toluca$size, conf.leve=0.90)

#zp=0.5*log((1+r)/(1-r));zp #Fisher transformation
#zpCI=zp+c(1,-1)*qnorm(0.05)*sqrt(1/(25-3));zpCI #CI for Fisher's

#(exp(2*zpCI)-1)/(exp(2*zpCI)+1) #Transform Fisher's CI to correlation coefficient CI
```

```{r bank data lack of fit}
bank <- read.csv("C:/Users/arthur22/Downloads/bank.csv")
bankR.mod<-lm(accounts~deposit, bank)
summary(bankR.mod)
anova(bankR.mod)
bankF.mod<-lm(accounts~as.factor(deposit),bank)
anova(bankR.mod, bankF.mod)
```

```{r toluca lack of fit test}
tolucaR.mod<-lm(hour~size, data=toluca)
tolucaF.mod<-lm(hour~factor(size),data=toluca)
plot(hour~size, toluca)
abline(tolucaR.mod)
summary(tolucaR.mod)
anova(tolucaR.mod)
anova(tolucaR.mod,tolucaF.mod)
```

```{r Lack of fit with Toluca no replicate}
tolucanr <- read.csv("C:/Users/arthur22/Downloads/tunr.csv")
tolucanrR.mod<-lm(y~x, data=tolucanr)
tolucanrF.mod<-lm(y~factor(x),data=tolucanr)

summary(tolucanrR.mod)
anova(tolucanrR.mod)
anova(tolucanrR.mod,tolucanrF.mod)


plot(y~x, tolucanr)
abline(tolucanrR.mod)
```

```{r lact of fit test without replica, simple grouping}
g<-c(30,30,30,60,60,60,90,90,90,115,115)
tolucanr$g<-g

tolucanrgR.mod<-lm(y~g, data=tolucanr)
tolucanrgF.mod<-lm(y~factor(g),data=tolucanr)
summary(tolucanrgR.mod)
anova(tolucanrgR.mod)
anova(tolucanrgR.mod,tolucanrgF.mod)

plot(y~g, tolucanr)
abline(tolucanrR.mod)

```

```{r simulate a perfect SLR data example for lack of fit}
x<-rep(seq(1:30),3)
y<-10*x+30+rnorm(90, 0,25)
SLRdata<-data.frame(x,y)
SLRdataRM<-lm(y~x, SLRdata)
plot(x,y)
abline(SLRdataRM)
summary(SLRdataRM)
anova(SLRdataRM)

SLRdataFM<-lm(y~as.factor(x),SLRdata)
anova(SLRdataFM)

summary(SLRdataRM)$sigma 
summary(SLRdataFM)$sigma

anova(SLRdataRM,SLRdataFM)


residualPlots(lm(y~x, SLRdata))
```

```{r simulated nonlinear data example for lack of fit}
x<-rep(seq(1:30),3)
y<-x^2-10*x+30+rnorm(90, 0,25)
nl<-data.frame(x,y)
nonlinearRM<-lm(y~x, nl)
plot(x,y)
abline(nonlinearRM)
summary(nonlinearRM)
anova(nonlinearRM)


nonlinearFM<-lm(y~as.factor(x),nl)
anova(nonlinearFM)

summary(nonlinearRM)$sigma 
summary(nonlinearFM)$sigma

anova(nonlinearRM,nonlinearFM)


residualPlots(lm(y~x, nl))
```

```{r simulated data example 1 for lack of fit}
x<-rep(seq(1:100),3)
y<-10*x+rexp(300, rate=1/200)
plot(x,y)
expo<-data.frame(x,y)
expoR.mod<-lm(y~x, expo)
summary(expoR.mod)
expoF.mod<-lm(y~factor(x),expo)
anova(expoR.mod,expoF.mod)
bptest(expoR.mod)

residualPlots(expoR.mod)
```

```{r simulated data example 2 for lack of fit}
x<-rep(seq(1:100),3)
y<-rep(10,300)
plot(x,y)
const<-data.frame(x,y)
constR.mod<-lm(y~x, const)
constF.mod<-lm(y~factor(x),const)
anova(constR.mod)
anova(constR.mod,constF.mod)
```

```{r boxplot for X}
summary(toluca$size)
mean(toluca$size)
boxplot(toluca$size, horizontal=TRUE, main="Box Plot for Lot size")
```

```{r residual vs X}
toluca.mod<-lm(hour~size, toluca)
residualPlots(toluca.mod, tests=TRUE, quadratic=FALSE, smooth=FALSE)
```

```{r create quad data}
x<-seq(1:30)
y<-x^2-10*x+30+rnorm(30,mean=0,sd=25)
quad<-data.frame(x,y)
quad.mod<-lm(y~x, quad)
summary(quad.mod)
plot(x,y)
abline(quad.mod)

anova(quad.mod)
#residquad<-residuals(quad.mod)
residualPlots(quad.mod)

nonlinearRM<-lm(y~x, nl)
plot(x,y)
abline(nonlinearRM)
summary(nonlinearRM)
anova(nonlinearRM)


nonlinearFM<-lm(y~as.factor(x),nl)
anova(nonlinearFM)

summary(nonlinearRM)$sigma 
summary(nonlinearFM)$sigma

anova(nonlinearRM,nonlinearFM)


```

```{r create heterocedasticity data}

x<-rep(c(31:100),3)
y<-30+100*x+rnorm(210,mean=0,sd=5*x)
het<-data.frame(x,y)
hetRM<-lm(y~x, het)
summary(hetRM)
plot(x,y)
abline(hetRM)
anova(hetRM)

hetFM<-lm(y~as.factor(x), het)
anova(hetRM)
anova(hetRM,hetFM)

residualPlots(hetRM)
```

```{r create data with non normal error}
x<-rep(c(1:100),3)
y<-10*x+rexp(300, rate=1/200)
expo<-data.frame(x,y)
expo.mod<-lm(y~x, expo)
summary(expo.mod)
plot(x,y)
abline(expo.mod)


expoFM<-lm(y~as.factor(x), expo)
anova(expo.mod,expoFM)
summary(expo.mod)$sigma
summary(expoFM)$sigma

anova(expo.mod)
exporesid<-residuals(expo.mod)
plot(x,exporesid)
abline(h=0)


residualPlots(expo.mod)

shapiro.test(exporesid)
qqnorm(exporesid)
qqline(exporesid)

m<-mean(exporesid)
std<-sqrt(var(exporesid))


h<-hist(exporesid, main="Normal curve over histogram")
xfit<-seq(min(exporesid),max(exporesid),length=100)
yfit<-dnorm(xfit,mean=m,sd=std)
yfit<-yfit*diff(h$mids[1:2])*length(exporesid)
lines(xfit, yfit, col="red", lwd=2)

multiplier<-(h$counts/h$density)[1]
mydensity<-density(exporesid)
mydensity$y<-mydensity$y*multiplier
lines(mydensity)
```

```{r SLR on the expo data}
x<-seq(1:100)
y<-10*x+rexp(100, rate=1/200)
expo<-data.frame(x,y)
expo.mod<-lm(y~x, expo)
c(coef(expo.mod),t(confint(expo.mod)))
```

```{r simulation one replication}
x<-seq(1:100)
y<-30+100*x+rnorm(100,mean=0,sd=5*x)
m<-lm(y~x)
c(coef(m),t(confint(m)))
```

```{r simulation CI}
f1<-function(){
  #x<-1:100
  #y<-10*x+rexp(100, rate=1/200)
  x<-seq(1:100)
  y<-30+100*x+rnorm(100,mean=0,sd=5*x)
  m<-lm(y~x)
  c(coef(m),t(confint(m)))
}

ci<-replicate(1000,f1())
coverage<-c(bo<-sum(30>ci[3,]& 30<ci[4,])/ncol(ci),
            b1<-sum(100>ci[5,]& 100<ci[6,])/ncol(ci)
            )
avgCI<-round(rowMeans(ci),2)


coverage

avgCI
```

```{r prediciton with violation}
x<-seq(1:300)
y<-10*x+rexp(300, rate=1/200)
expo<-data.frame(x,y)
expo.mod<-lm(y~x, expo)
cin<-ci.reg(expo.mod, expo$x, type='n',alpha=0.05)
plot(y~x, expo, main="prediciton")
abline(expo.mod)
lines(expo$x, cin$Lower.Band,col="blue", lwd=2, lty=3)
lines(expo$x, cin$Upper.Band, col="blue", lwd=2, lty=3)

```

```{r outlier near x mean}
x1<-seq(1:100)
x2<-c(x1,50)
y1<-30+50*x1+rnorm(100,mean=0,sd=200)
y2<-c(y1,30+50*50-10000)
nooutlier<-data.frame(x1,y1)
outlier50<-data.frame(x2,y2)

nooutlier.mod<-lm(y1~x1, nooutlier)

summary(nooutlier.mod)
resid1<-residuals(nooutlier.mod)
outlier50.mod<-lm(y2~x2, outlier50)
resid2<-residuals(outlier50.mod)

summary(outlier50.mod)

plot(x1,y1)
abline(nooutlier.mod)

plot(x2, y2)
abline(outlier50.mod)

```

```{r outlier near x max}
x1<-seq(1:100)
x3<-c(x1,100)
y1<-30+50*x1+rnorm(100,mean=0,sd=200)
y3<-c(y1,30+50*50-10000)
nooutlier<-data.frame(x1,y1)
outlier100<-data.frame(x3,y3)


outlier100.mod<-lm(y3~x3, outlier100)
resid3<-residuals(outlier100.mod)
summary(outlier100.mod)

plot(x3, y3)
abline(outlier100.mod)

```

```{r Brown-Forsythe Test between two groups only}
g<-rep(1,25)
g[toluca$size<=70]=0     #form two groups
bftest(lm(hour~size, toluca),g)
```

```{r Brown-Forsythe test between n groups }
toluca$group<-cut(toluca$size, 5)  #form five groups
toluca$residual<-toluca.mod$residuals
bf.test(residual~group, toluca )   
```

```{r BP test}
bptest(lm(hour~size, toluca))

```

```{r}
g<-10
qt(1-0.1/(2*g), 23)
```

```{r}
qt(0.95, 46)

(1-pt(2.702,46))

qf(0.95,3, 18)
sqrt(3*qf(0.95,3, 18))
```

```{r}
plasma <- read.csv("C:/Users/arthur22/Downloads/plasma.csv")
colnames(plasma)
summary(plasma)
```

```{r}
plasma.mod<-lm(plasma~age, plasma)
plot(plasma~age, plasma)
abline(plasma.mod)
summary(plasma.mod)
anova(plasma.mod)
#plot(plasma.mod)

resid<-residuals(plasma.mod)
plot(plasma$age,resid)
abline(h=0)
```

```{r Lack of fit test}
plasmaR.mod<-lm(plasma~age,plasma)
plasmaF.mod<-lm(plasma~factor(age), plasma)
anova(plasmaR.mod)
anova(plasmaR.mod, plasmaF.mod) # lack of fit test
```

```{r Diagnostics}
#shapiro.test(residuals(plasma.mod))
#qqnorm(residuals(plasma.mod))
#qqline(residuals(plasma.mod))
g<-rep(1,25)
g[plasma$age==0]=0     #form two groups
bftest(plasma.mod,g)
g

plasma$residual<-plasma.mod$residuals
plasma$agef<-factor(plasma$age) #convert integer to factor type
plasma$agef
bf.test(residual~agef, plasma)   #the Brown-Forsythe test for constant variance
```

```{r Confidence Interval Band}

x<-data.frame(weight=unique(plasma$age))

cim<-ci.reg(plasma.mod, x, type='m',alpha=0.05)
cin<-ci.reg(plasma.mod, x, type='n',alpha=0.05)

plot(plasma ~ age, plasma, main="Prediction Confidence Interval ")
abline(plasma.mod)

lines(cim$age, cim$Lower.Band,col="green", lwd=2, lty=1)
lines(cim$age, cim$Upper.Band, col="green", lwd=2, lty=1)
lines(cin$age, cin$Lower.Band,col="blue", lwd=2, lty=2)
lines(cin$age, cin$Upper.Band, col="blue", lwd=2, lty=2)

legend(x=2, y=20, legend=c("Predicting mean confidence band","Predicting individual confidence band"), lty=c(1,2), col=c("green","blue"),cex=0.8, bty="n")
```

```{r Residual Diagnostics}
pu <- read.csv("C:/Users/arthur22/Downloads/plutonium.csv")
pu.mod<-lm(alpha~plutonium, pu)

plot(alpha~plutonium, pu)
abline(pu.mod)
identify(x, plot=TRUE)

plot(pu.mod$residuals~plutonium,pu)
abline(h=0)
summary(pu.mod)
anova(pu.mod)
plot(pu.mod)
```

```{r Remove Case 24}
pu<-pu[-24,]

pu.mod<-lm(alpha~plutonium, pu)

plot(alpha~plutonium, pu)
abline(pu.mod)
identify(x, plot=TRUE)

plot(pu.mod$residuals~plutonium,pu)
abline(h=0)
summary(pu.mod)
anova(pu.mod)
plot(pu.mod)

pu$residual<-pu.mod$residuals
pu$x<-factor(pu$plutonium) #convert integer to factor type
bf.test(residual~x, pu) 

shapiro.test(pu$residual)
```

```{r Lack of Fit Test}
puR.mod<-lm(alpha~plutonium, pu)
puF.mod<-lm(alpha~factor(plutonium), pu)
anova(puR.mod)
anova(puR.mod, puF.mod) # lack of fit test

```

```{r Confidence Bands}
x<-data.frame(plutonium=sort(unique(pu$plutonium)))
cim<-ci.reg(pu.mod, x, type='m',alpha=0.05)
cin<-ci.reg(pu.mod, x, type='n',alpha=0.05)


plot(alpha ~ plutonium, pu, main="Confidence Bands")

lines(cim$plutonium, cim$Lower.Band,col="green", lwd=2, lty=2)
lines(cim$plutonium, cim$Upper.Band, col="green", lwd=2, lty=2)
lines(cin$plutonium, cin$Lower.Band,col="blue", lwd=2, lty=3)
lines(cin$plutonium, cin$Upper.Band, col="blue", lwd=2, lty=3)


legend(x=0, y=0.12, legend=c("Predicting mean confidence band","Predicting individual confidence band"), lty=c(2,3), col=c("green","blue"),cex=0.8, bty="n")
```

```{r}
a=0.1
g=5
qt(1-a/(2*g),23)
```

```{r}
a=0.05
g=2
sqrt(g*qf(1-a,g, 200))
```

```{r}
bcmle<-boxcox(lm(plasma~age,data=plasma),lambda=seq(-3,3, by=0.1))
bcmle
lambda<-bcmle$x[which.max(bcmle$y)]
lambda

```

```{r}
a<-cbind(c(1,2),c(3,4))
a
b<-cbind(c(1,3),c(2,4))
b
a*b
a%*%b

```

```{r Boxcox, Min SSE}
bcsse<-boxcox.sse(plasma$age,plasma$plasma,l=seq(-2,2,0.1))
lambda<-bcsse$lambda[which.min(bcsse$SSE)]
lambda
```

```{r confidence band}
plasma$ty<-1/sqrt(plasma$plasma)
plasmaT.mod<-lm(ty~age, plasma)
x<-data.frame(weight=unique(plasma$age))


cim<-ci.reg(plasmaT.mod, x, type='m',alpha=0.05)
cin<-ci.reg(plasmaT.mod, x, type='n',alpha=0.05)


plot(ty ~ age, plasma, main="Confidence Bands before back transformation")

lines(cim$age, cim$Lower.Band,col="green", lwd=2, lty=2)
lines(cim$age, cim$Upper.Band, col="green", lwd=2, lty=2)
lines(cin$age, cin$Lower.Band,col="blue", lwd=2, lty=3)
lines(cin$age, cin$Upper.Band, col="blue", lwd=2, lty=3)


legend(x=2, y=0.25, legend=c("Predicting mean confidence band","Predicting individual confidence band"), lty=c(2,3), col=c("green","blue"),cex=0.8, bty="n")
```

```{r CI after back trasformation }
plasma$ty<-1/sqrt(plasma$plasma)
plasmaT.mod<-lm(ty~age, plasma)

plasmaT.mod$fitted.values<-plasmaT.mod$fitted.values^(-2)
plasmaT.mod$fitted.values

x<-data.frame(weight=unique(plasma$age))


cim<-ci.reg(plasmaT.mod, x, type='m',alpha=0.05)
cin<-ci.reg(plasmaT.mod, x, type='n',alpha=0.05)


plot(plasma ~ age, plasma, main="Confidence Bands after back transformation")

lines(cim$age, (cim$Lower.Band)^(-2),col="green", lwd=2, lty=2)
lines(cim$age, (cim$Upper.Band)^(-2), col="green", lwd=2, lty=2)
lines(cin$age, (cin$Lower.Band)^(-2),col="blue", lwd=2, lty=3)
lines(cin$age, (cin$Upper.Band)^(-2), col="blue", lwd=2, lty=3)


legend(x=2, y=15, legend=c("Predicting mean confidence band","Predicting individual confidence band"), lty=c(2,3), col=c("green","blue"),cex=0.8, bty="n")

```